appVersion: 5.0.0
deprecated: true
description: DEPRECATED - Open Source Identity and Access Management For Modern Applications
  and Services
home: https://www.keycloak.org/
icon: https://www.keycloak.org/resources/images/keycloak_logo_480x108.png
keywords:
- sso
- idm
- openid connect
- saml
- kerberos
- ldap
name: keycloak
sources:
- https://github.com/jboss-dockerfiles/keycloak
version: 4.10.1
