apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-sealed-secret
  namespace: default
spec:
  encryptedData:
    password: AgAvULf7cGifRIc2r1+qRLEdeTRg27TUFmOY0omRSWe4jvn+mQVFRKwW1T5raNmjyb7bGK2dE6+1xRmJ5+eVP2TDGYKovNWSj8bnbvPPuP9yrhr1EWB4TktvexXXOK4+9V6+UbU+jQjbsn5yl8Hk9rT+LO+iu2xhEJKibZAGh6euWPfITrCbBBr+/t+J7JxdmsLAb/C5P31TXEi2zyHZbxsyztNsYC0Mzf1gTHiFZRFSLSCSEy7MCgpp7VGaXi1E17t29THvq9xHfpDjr1GAd+j9aszA4J8Uo6TPNH+TSo9jV4r6O+9HbpergWQZM4rhSyAyL84OeG4YLJK16Qn0mwS51spUJ/SwXscRMHDB8EzDYQ0EMfT4hc7UHRoeJbQ58v963yP3ZO+C3fwoRC45k74Iian0PdUSlspFqW3iCewlGmpuoaWoe+j8U3s6VkBQAkMSAJtqAheuG1WXrkT4OaWCB957yWsWbejXF8zhQU3+vBZ9hD1c1VblCrbsJbbHglEj2gFZTZKHZnxiEVct4BXZDH+1O+vEG0gQxWOtkqrPSS7AN2+aCXqOraTzbCP7grNLEGxb2llV5JTDEx+WNCYGKSRC5TJ7TEg+l4RQkVxH7TtKZyWaCmA98gQLdxSaqGMggdhGzbWvVyotK1GNObI2aRoAcvDiR0IFZqm8+fecHlo+JiwIB4A8cpEQC81IIDOvhY+SJZCBWw==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-sealed-secret
      namespace: default
status: {}

